// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaPagosServiceBus.Data;

#nullable disable

namespace SistemaPagosServiceBus.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaPagosServiceBus.Models.EventoTransaccion", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int");

                    b.HasKey("EventoId");

                    b.HasIndex("TransaccionId");

                    b.ToTable("EventosTransaccion");

                    b.HasData(
                        new
                        {
                            EventoId = 1,
                            Descripcion = "Pago autorizado por el banco",
                            FechaEvento = new DateTime(2024, 2, 10, 10, 16, 30, 0, DateTimeKind.Unspecified),
                            TipoEvento = "Transacción aprobada",
                            TransaccionId = 1
                        },
                        new
                        {
                            EventoId = 2,
                            Descripcion = "Esperando validación de fondos",
                            FechaEvento = new DateTime(2024, 2, 12, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            TipoEvento = "Transacción creada",
                            TransaccionId = 2
                        },
                        new
                        {
                            EventoId = 3,
                            Descripcion = "Saldo insuficiente",
                            FechaEvento = new DateTime(2024, 2, 8, 18, 46, 10, 0, DateTimeKind.Unspecified),
                            TipoEvento = "Transacción fallida",
                            TransaccionId = 3
                        });
                });

            modelBuilder.Entity("SistemaPagosServiceBus.Models.Notificacion", b =>
                {
                    b.Property<int>("NotificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacionId"));

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("EstadoNotificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int");

                    b.HasKey("NotificacionId");

                    b.HasIndex("TransaccionId")
                        .IsUnique();

                    b.ToTable("Notificaciones");

                    b.HasData(
                        new
                        {
                            NotificacionId = 1,
                            EmailCliente = "cliente1@email.com",
                            EstadoNotificacion = "Enviada",
                            FechaEnvio = new DateTime(2024, 2, 10, 10, 17, 0, 0, DateTimeKind.Unspecified),
                            TransaccionId = 1
                        });
                });

            modelBuilder.Entity("SistemaPagosServiceBus.Models.Transaccion", b =>
                {
                    b.Property<int>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaccionId"));

                    b.Property<string>("CuentaDestino")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("DetallesAdicionales")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNotificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaProcesamiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransaccionId");

                    b.HasIndex("Estado");

                    b.ToTable("Transacciones");

                    b.HasData(
                        new
                        {
                            TransaccionId = 1,
                            CuentaDestino = "4532123412341234",
                            DetallesAdicionales = "Compra portátil gaming",
                            Estado = "Exitosa",
                            FechaCreacion = new DateTime(2024, 2, 10, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            FechaNotificacion = new DateTime(2024, 2, 10, 10, 17, 0, 0, DateTimeKind.Unspecified),
                            FechaProcesamiento = new DateTime(2024, 2, 10, 10, 16, 30, 0, DateTimeKind.Unspecified),
                            Monto = 450.90m,
                            TipoTransaccion = "PagoConTarjeta"
                        },
                        new
                        {
                            TransaccionId = 2,
                            CuentaDestino = "ES9121000418450200051332",
                            DetallesAdicionales = "Pago mensual alquiler",
                            Estado = "Pendiente",
                            FechaCreacion = new DateTime(2024, 2, 12, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Monto = 1200.00m,
                            TipoTransaccion = "TransferenciaBancaria"
                        },
                        new
                        {
                            TransaccionId = 3,
                            CuentaDestino = "5555444433332222",
                            DetallesAdicionales = "Suscripción plataforma streaming",
                            Estado = "Fallida",
                            FechaCreacion = new DateTime(2024, 2, 8, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            FechaProcesamiento = new DateTime(2024, 2, 8, 18, 46, 10, 0, DateTimeKind.Unspecified),
                            Monto = 89.99m,
                            TipoTransaccion = "PagoConTarjeta"
                        });
                });

            modelBuilder.Entity("SistemaPagosServiceBus.Models.EventoTransaccion", b =>
                {
                    b.HasOne("SistemaPagosServiceBus.Models.Transaccion", "Transaccion")
                        .WithMany("Eventos")
                        .HasForeignKey("TransaccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("SistemaPagosServiceBus.Models.Notificacion", b =>
                {
                    b.HasOne("SistemaPagosServiceBus.Models.Transaccion", "Transaccion")
                        .WithOne("Notificacion")
                        .HasForeignKey("SistemaPagosServiceBus.Models.Notificacion", "TransaccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("SistemaPagosServiceBus.Models.Transaccion", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Notificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
